### ISSUE TITLE
matplotlib error during plotHIFIoutput.py running

### ISSUE THREAD

**Issue by wsuplantpathology** [BlanchetteLab/HIFI#4]
Hi HIFI:

Thanks for such a nice tool. I was testing the example data, the `../src/HIFI` step went well, but got some error during plotHIFIoutput.py running. The code was `python2 ../src/plotHIFIoutput.py examples_output/Rao_GM12878.hg19.chr9_example.chr9_chr9.RF.HIFI_MRF.125000000_129000000.tsv hg19.HindIII_fragments.bed 0.0 1.5 examples_output/`.

The error message is:
`Building HIFI sparse matrix ...  Done
Importing restriction fragment information ...  Done
Plotting full matrix ... Traceback (most recent call last):
  File "../src/plotHIFIoutput.py", line 179, in <module>
    plotSparseMatrix(matrix,chrom,args.vmin,args.vmax,RF_dict,output_directory+output_filename)
  File "../src/plotHIFIoutput.py", line 130, in plotSparseMatrix
    cbar=plt.colorbar(pc,fraction=0.04575,pad=0.04)
  File "/opt/apps/python/2.7.10_shared/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2261, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/opt/apps/python/2.7.10_shared/lib/python2.7/site-packages/matplotlib/figure.py", line 1603, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **kw)
  File "/opt/apps/python/2.7.10_shared/lib/python2.7/site-packages/matplotlib/colorbar.py", line 1347, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/opt/apps/python/2.7.10_shared/lib/python2.7/site-packages/matplotlib/colorbar.py", line 926, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "/opt/apps/python/2.7.10_shared/lib/python2.7/site-packages/matplotlib/colorbar.py", line 326, in __init__
    self.draw_all()
  File "/opt/apps/python/2.7.10_shared/lib/python2.7/site-packages/matplotlib/colorbar.py", line 347, in draw_all
    self._process_values()
  File "/opt/apps/python/2.7.10_shared/lib/python2.7/site-packages/matplotlib/colorbar.py", line 686, in _process_values
    expander=0.1)
  File "/opt/apps/python/2.7.10_shared/lib/python2.7/site-packages/matplotlib/transforms.py", line 2773, in nonsingular
    if (not np.isfinite(vmin)) or (not np.isfinite(vmax)):
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
`

It seems something went wrong with matplotlib, but I am nof familiar with matplotlib, hope you can help with this. Here are more info, `python version 2.7.10`, `matplotlib version 2.0.2`. Thanks.

Best,
Chongjing

**Comment by ccameron** [comment]
Please check that valid input was provided to the plotHIFIoutput.py script. This error appears to result from a matplotlib color bar issue, which may occur when the input or plotted matrix has unexpected values.

**Comment by ccameron** [comment]
@ebioman could you please check that the input matrix you're providing to `plotHIFIoutput.py` is valid? i.e., is it similar to the screenshot below
The error that you are encountering is from NumPy, which usually occurs when `isfinite()` is applied to a non-numeric value.
<img width="924" alt="Screen Shot 2022-09-24 at 3 42 01 PM" src="https://user-images.githubusercontent.com/30734249/192115748-4efd5ffc-9801-490d-9741-2ed4ef48dfb4.png">

**Comment by ccameron** [comment]
@ebioman thanks for the additional information.

The file content looks good and we have the same line count for the toy example.

I wonder if it's an issue with the command line parsing and argument data types. I updated the `plotHIFIoutput.py` script to explicitly set the vmin / vmax values to float type. I have also added multiple assertion checks to the script (e.g., check that vmin / vmax are of the right type, all elements of the NumPy matrix are type float). Could you please try plotting the HIFI output with the updated script? Hopefully, this will help us track down the reason for the error.

In addition, could you check the sum of values in the HIFI output file:

`awk 'NR>1 {FS = "\t"; count += $1} END {print count}' Rao_GM12878.hg19.chr9_example.chr9_chr9.RF.HIFI_MRF.125000000_129000000.tsv` 

I get a sum of 6.29817e+10 for the toy example.

The relevant software versions I've successfully tested the current repo on are:
- Python 2.7.15, NumPy 1.15.4, Matplotlib 2.2.5
- Python 3.7.11, NumPy 1.20.3, Matplotlib 3.4.2

**Comment by ebioman** [comment]
@ccameron thanks, that seems to do the trick! I checked the sum of values which was before already good.
When running your patched plotting script it now succeeds and does not anymore produce any erros

**Comment by ccameron** [comment]
@ebioman fantastic! I'm glad those changes solved the error.
I'm going to close this issue now as I suspect this issue was the cause of the OP.
